# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0161dd5a2102cdd47deeb875a97fa8f4a65c2d3a810d731e87e3d09071322b6a5f8f6fffa5a698b7e55ea5b48b41ff95c62061506a301e8e31d55746e373e4f5

test:
  secret_key_base: da4ed492c37fe3c81ddef44198a2d78852aff0c2d4079f1ccf885daf11564786eba91c10fcaff5f51844d21120e7c66ecd94e82de3fddcc3f5622f4f93adef5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
